// Generated by CoffeeScript 1.6.3
(function() {
  this.Movies = Backbone.Collection.extend({
    model: Movie,
    comparator: function(movie) {
      return movie.get('ranking');
    },
    initialize: function() {
      console.log("A Collection is initialized");
      console.log(this);
      console.log(JSON.stringify(this));
      return console.log("***************");
    }
  });

}).call(this);
