// Generated by CoffeeScript 1.6.3
(function() {
  this.Movie = Backbone.Model.extend({
    defaults: {
      title: 'Avasd',
      gross: 0,
      rank: -1,
      year: 1900,
      studio: 'Stud'
    },
    initialize: function() {
      console.log("A Model is initialized");
      console.log(this);
      console.log(JSON.stringify(this));
      return console.log("===============");
    }
  });

}).call(this);
